workflows:
  build-ios:
    name: Build iOS WebView App
    instance_type: mac_mini_m2
    environment:
      vars:
        CAPACITOR_PROJECT_PATH: "."
      xcode: latest
      cocoapods: default
    scripts:
      - name: Instalar dependências
        script: |
          npm install
      - name: Build frontend (HTML)
        script: |
          echo "Nada para compilar, HTML puro"
      - name: Sincronizar Capacitor
        script: |
          chmod +x ./node_modules/.bin/cap
          npx cap sync ios
      - name: Build iOS com Xcode
        script: |
          cd ios/App
          xcodebuild -project App.xcodeproj -scheme App -configuration Release -destination generic/platform=iOS

    artifacts:
      - build/ios/ipa/*.ipa
